In [22]:
import numpy as np
import pandas as pd

In [23]:
import re

In [24]:
df = pd.DataFrame();
for i in range(0,981,20):
    path = './data/f{}t{}/cars.txt'.format(i,i+19);
    #print(path)
    df1 = pd.read_table(path, sep='\t', header=None);
    df = pd.concat([df, df1], axis=0);
df = df.reset_index(drop=True);
df.columns = ['Year_Make_Model','Price','Mileage','Body','Color','Engine'];

print("-"*10 + " Raw Data " + "-"*10)
print(df.shape)

print("-"*10 + " Drop $Price == N/A " + "-"*10)
df = df.loc[df.Price.str.startswith('$')]
print(df.shape)

print("-"*10 + " Drop $Mileage == N/A " + "-"*10)
df = df.loc[df.Mileage!='N/A miles']
print(df.shape)


df.head(10)

print("-"*50)

# Column Year_Make_Model splits into three columns: Year, Make, Model
df['Year'] = \
list(map(lambda str4: str4[0],\
         list( map( lambda strLong: strLong.split(sep=' '), df.Year_Make_Model ) )));
df['Year'] = pd.to_numeric(df.Year);
df['Make'] = \
list(map(lambda str4: str4[1],\
         list( map( lambda strLong: strLong.split(sep=' '), df.Year_Make_Model ) )));
df['Model'] = \
list(map(lambda str4: str4[2],\
         list( map( lambda strLong: strLong.split(sep=' '), df.Year_Make_Model ) )));

print("-"*10 + " Drop $Make == Land " + "-"*10)
print('# Land Rover Range Rover:')
print('Not worth the efforts to go extra hours to fix this!')
# Land Rover Range Rover ## not worth the efforts to go extra miles to fix this
df = df.loc[df.Make!='Land']
print(df.shape)

df.head()

---------- Raw Data ----------
(21752, 6)
---------- Drop $Price == N/A ----------
(21723, 6)
---------- Drop $Mileage == N/A ----------
(21693, 6)
--------------------------------------------------
---------- Drop $Make == Land ----------
# Land Rover Range Rover:
Not worth the efforts to go extra hours to fix this!
(21630, 9)

,Year_Make_Model,Price,Mileage,Body,Color,Engine,Year,Make,Model
0,2014 Dodge Grand Caravan SE,"$9,999","99,252 miles",Minivan,Black,6 Cyl,2014,Dodge,Grand
1,2014 Dodge Avenger SE,"$6,495","102,034 miles",Sedan,Black,4 Cyl,2014,Dodge,Avenger
2,2016 Jeep Wrangler Sahara,"$33,688","15,674 miles",SUV,Red,6 Cyl,2016,Jeep,Wrangler
3,2011 BMW 3 Series 328i,"$10,966","100,273 miles",Convertible,Silver,6 Cyl,2011,BMW,3
4,2015 Ford Explorer XLT,"$24,983","23,640 miles",SUV,White,6 Cyl,2015,Ford,Explorer

In [25]:
## Not working properly!

#df[(df.Make=='Jeep') & (df.Model=='Grand')] = \
#df[(df.Make=='Jeep') & (df.Model=='Grand')].replace('Grand','Grand_Cherokee')

#(272, 9)

In [26]:
# Price to numerics
df.Price = list(map(lambda str0: str0[1:].replace(',',''), df.Price));
df.Price = pd.to_numeric(df.Price);

# Mileage to numerics
df.Mileage = list(map(lambda str0: str0.replace(' miles', '').replace(',',''), df.Mileage));
df.Mileage = pd.to_numeric(df.Mileage);

df = df[['Year','Make','Model','Mileage','Price','Body','Color','Engine']];
df.head()

   Year   Make     Model  Mileage  Price          Body    Color  Engine
0  2014  Dodge     Grand    99252   9999      Minivan    Black   6 Cyl
1  2014  Dodge   Avenger   102034   6495        Sedan    Black   4 Cyl
2  2016   Jeep  Wrangler    15674  33688          SUV      Red   6 Cyl
3  2011    BMW         3   100273  10966  Convertible   Silver   6 Cyl
4  2015   Ford  Explorer    23640  24983          SUV    White   6 Cyl

In [27]:
for i in df.columns:
    print(i)
    print(df[i].unique())
    print('-'*70)

Year
[2014 2016 2011 2015 2013 2017 2007 2012 2008 2006 2004 2005 2009 2010 2003
 2002 2001 2018 1985 1990 1998 2000 1999 1996]
----------------------------------------------------------------------
Make
['Dodge' 'Jeep' 'BMW' 'Ford' 'Nissan' 'GMC' 'Chevrolet' 'Lincoln' 'Honda'
 'Kia' 'Toyota' 'Mercedes-Benz' 'Mitsubishi' 'Infiniti' 'Cadillac' 'Hummer'
 'Maserati' 'Volkswagen' 'Subaru' 'Audi' 'Mini' 'Lexus' 'Acura' 'Mazda'
 'Volvo' 'Hyundai' 'Buick' 'Porsche' 'Chrysler' 'Jaguar' 'Scion' 'Ram'
 'Fiat' 'Pontiac' 'Saturn' 'Mercury' 'Suzuki' 'Saab' 'Oldsmobile' 'Genesis']
----------------------------------------------------------------------
Model
['Grand' 'Avenger' 'Wrangler' '3' 'Explorer' 'Juke' 'F-250' 'Sierra'
 'Cruze' 'Mustang' 'MKC' 'Pilot' 'Challenger' 'Rio' 'Suburban' '4Runner'
 'Trax' 'C-Class' 'F-150' 'Tahoe' 'Optima' 'Outlander' 'Escape' 'G35' 'Q50'
 'Rogue' 'CTS' 'X5' 'Camry' 'Civic' 'Accord' 'Altima' 'H3' 'Maxima'
 'Ghibli' 'GranTurismo' 'G37' 'Taurus' 'Tiguan' 'M-Class' 'Corolla'
 'Outback' 'Passat' 'A6' 'Sienna' 'Colorado' 'Murano' 'Charger' 'Escalade'
 'Jetta' 'GLK' 'Q5' 'Silverado' 'Cooper' 'S5' 'RX' 'CLA' '5' 'A5' 'A7'
 'Pathfinder' 'MDX' 'Traverse' 'GLA' 'ILX' 'Mazda3' 'Versa' 'MKZ' 'Quest'
 'XC90' 'IS' 'Dart' 'CLS' 'Cherokee' 'Venza' 'RAV4' 'Routan' 'Highlander'
 'Santa' 'GS' 'XC60' 'Focus' 'Element' 'V70' 'Monte' 'Fiesta' 'A4' 'Fusion'
 'TL' 'Corvette' 'CR-V' 'Encore' 'Prius' '4' 'Soul' 'Acadia' 'NX' 'S-Class'
 'Q3' 'Durango' 'EX35' 'Journey' 'Elantra' 'Sentra' 'Malibu' '911' 'ES'
 'TrailBlazer' '300' 'X1' 'Regal' 'Pacifica' 'GLC' 'CX-9' 'Avalon'
 'Touareg' 'Renegade' 'Sedona' 'Edge' 'Enclave' 'Expedition' 'Camaro'
 'Forte' 'Patriot' 'Tundra' 'Sonata' 'Verano' 'TSX' 'Z' 'Legacy'
 'Avalanche' 'Transit' 'Ram' 'Dakota' 'XF' 'ATS' 'CC' 'X3' 'Odyssey'
 'Equinox' 'RDX' 'MKX' 'Tacoma' 'FR-S' '200' 'SRX' 'Envoy' 'PT' 'Spectra'
 'LX' 'E-Class' 'Terrain' 'Liberty' 'Town' 'GL-Class' '2' 'CX-5' 'GLE'
 'TLX' 'Cadenza' 'SLK' 'S60' 'A3' 'Beetle' 'Genesis' 'X6' 'Titan' '1500'
 'Frontier' 'Forester' 'Sorento' 'Mirage' '2500' 'GX' 'Eos' 'XT5' 'Sequoia'
 'Yukon' 'F-350' 'SQ5' 'New' 'RSX' 'DTS' 'WRX' 'Ridgeline' 'Cayman' 'S4'
 '500' 'iM' 'Flex' 'Spark' 'M4' 'Veloster' 'M3' 'F-Type' 'Impreza'
 'R-Class' '500L' 'Q70' 'Accent' 'C-Max' 'Sportage' 'Q7' 'Tribute' 'Golf'
 'Azera' 'QX60' 'MKS' 'RC' 'X4' 'XJ' 'A8' 'Miata' 'M5' '1' 'CR-Z' 'QX80'
 'LS' 'HHR' 'CX-7' 'Sonic' 'Tucson' 'Yaris' '7' 'C70' 'tC' 'SRT' 'Mazda6'
 'S3' 'Crossfire' 'G6' 'V60' 'TT' 'Armada' 'XTS' 'QX30' 'Cascada' 'CLK'
 'X-Type' 'Mazda5' 'Eurovan' 'Outlook' 'XV' 'Crosstrek' 'Panamera' 'RS7'
 'Xterra' 'S80' 'STS' 'Impala' 'Canyon' '6' '500X' 'Insight' 'SL-Class'
 'Cayenne' 'BRZ' 'Matrix' 'Ranger' 'Solstice' 'Compass' 'Mazda2'
 'Navigator' 'Lancer' 'RL' 'xA' 'K900' 'LeSabre' 'xB' 'Volt' '3500' 'ELR'
 'ProMaster' 'C/V' 'Sunfire' 'Vibe' 'Fit' 'M35' 'Q60' 'S90' 'Aveo'
 'Econoline' 'Macan' 'S-Type' 'CT6' 'Allroad' 'iA' 'SS' 'FJ' 'SC' 'LC'
 'CL-Class' 'NV' 'Quattroporte' 'CX-3' 'LaCrosse' 'SLC' 'i8' 'i3' '86'
 'Cube' 'Boxster' 'Land' 'Equator' 'HR-V' '124' 'Q40' 'VUE' 'G8' '9-5' 'xD'
 'SX4' '9-3' 'MAZDASPEED3' 'R8' 'CT' 'RS4' 'Continental' 'MKT' 'Nitro'
 'Mariner' 'Envision' 'M6' 'Commander' 'Eldorado' 'Imperial' 'Alero' 'Neon'
 'Torrent' 'Magnum' 'XC70' 'Equus' 'Leaf' 'G80' 'RX-8' 'B-Series' 'Caravan'
 'S-10' 'Ion' 'Eclipse' 'Mountaineer' 'S6' 'Lucerne' 'Rio5' 'Excursion'
 'NV200' 'Forte5' 'Veracruz' 'MPV' 'Rabbit' 'Montero' 'Rendezvous' 'V50'
 'Z4' 'Captiva' 'Niro' 'Caliber' 'GLS' 'Milan' 'FX37' 'GTI' 'HS' 'Tribeca'
 'Express' 'QX56']
----------------------------------------------------------------------
Mileage
[ 99252 102034  15674 ...,  66066  38946  70161]
----------------------------------------------------------------------
Price
[ 9999  6495 33688 ..., 25125 28403 46462]
----------------------------------------------------------------------
Body
['Minivan\xa0' 'Sedan\xa0' 'SUV\xa0' 'Convertible\xa0' 'Pickup\xa0'
 'Coupe\xa0' 'Wagon\xa0' 'Hatchback\xa0' 'Van\xa0' 'Chassis\xa0']
----------------------------------------------------------------------
Color
['Black\xa0' 'Red\xa0' 'Silver\xa0' 'White\xa0' 'Yellow\xa0' 'Gray\xa0'
 'Brown\xa0' 'Beige\xa0' 'Blue\xa0' 'Green\xa0' 'Unspecified\xa0'
 'Gold\xa0' 'Turquoise\xa0' 'Burgundy\xa0' 'Bronze\xa0' 'Orange\xa0'
 'Purple\xa0']
----------------------------------------------------------------------
Engine
['6 Cyl\xa0' '4 Cyl\xa0' '8 Cyl\xa0' '5 Cyl\xa0' '3 Cyl\xa0' '10 Cyl\xa0'
 '2 Cyl\xa0' 'Electric\xa0' '12 Cyl\xa0' 'Rotary\xa0']
----------------------------------------------------------------------

In [28]:
df.columns

Index(['Year', 'Make', 'Model', 'Mileage', 'Price', 'Body', 'Color', 'Engine'], dtype='object')

In [29]:
# Remove extra string '\xa0' in $Body 
df.Body = list(map(lambda str0: str0.replace('\xa0', ''), df.Body));

In [30]:
# Remove extra string '\xa0' in $Color 
df.Color = list(map(lambda str0: str0.replace('\xa0', ''), df.Color));
df = df.loc[df.Color!='Unspecified']
print("-"*10 + " Drop $Color == Unspecified " + "-"*10)
print(df.shape)

---------- Drop $Color == Unspecified ----------
(20969, 8)

In [31]:
# Remove extra string '\xa0' in $Engine 
df.Engine = list(map(lambda str0: str0.replace('\xa0', ''), df.Engine));

In [32]:
for i in df.columns:
    print(i)
    print(df[i].unique())
    print('-'*70)

Year
[2014 2016 2011 2015 2013 2017 2007 2012 2008 2006 2004 2005 2009 2010 2003
 2002 2001 2018 1985 1990 1998 2000 1999]
----------------------------------------------------------------------
Make
['Dodge' 'Jeep' 'BMW' 'Ford' 'Nissan' 'GMC' 'Chevrolet' 'Lincoln' 'Honda'
 'Kia' 'Toyota' 'Mercedes-Benz' 'Mitsubishi' 'Infiniti' 'Cadillac' 'Hummer'
 'Maserati' 'Volkswagen' 'Subaru' 'Audi' 'Mini' 'Lexus' 'Acura' 'Mazda'
 'Volvo' 'Hyundai' 'Buick' 'Porsche' 'Chrysler' 'Jaguar' 'Scion' 'Ram'
 'Fiat' 'Pontiac' 'Saturn' 'Mercury' 'Suzuki' 'Saab' 'Oldsmobile' 'Genesis']
----------------------------------------------------------------------
Model
['Grand' 'Avenger' 'Wrangler' '3' 'Explorer' 'Juke' 'F-250' 'Sierra'
 'Cruze' 'Mustang' 'MKC' 'Pilot' 'Challenger' 'Rio' 'Suburban' '4Runner'
 'Trax' 'C-Class' 'F-150' 'Tahoe' 'Optima' 'Outlander' 'Escape' 'G35' 'Q50'
 'Rogue' 'CTS' 'X5' 'Camry' 'Civic' 'Accord' 'Altima' 'H3' 'Maxima'
 'Ghibli' 'GranTurismo' 'G37' 'Taurus' 'Tiguan' 'M-Class' 'Corolla'
 'Outback' 'Passat' 'A6' 'Sienna' 'Colorado' 'Murano' 'Charger' 'Escalade'
 'Jetta' 'GLK' 'Q5' 'Silverado' 'Cooper' 'S5' 'RX' 'CLA' '5' 'A5' 'A7'
 'Pathfinder' 'MDX' 'Traverse' 'GLA' 'ILX' 'Mazda3' 'Versa' 'MKZ' 'Quest'
 'XC90' 'IS' 'Dart' 'CLS' 'Cherokee' 'Venza' 'RAV4' 'Routan' 'Highlander'
 'Santa' 'GS' 'XC60' 'Focus' 'Element' 'V70' 'Monte' 'Fiesta' 'A4' 'Fusion'
 'TL' 'Corvette' 'CR-V' 'Encore' 'Prius' '4' 'Soul' 'Acadia' 'NX' 'S-Class'
 'Q3' 'Durango' 'EX35' 'Journey' 'Elantra' 'Sentra' 'Malibu' '911' 'ES'
 'TrailBlazer' '300' 'X1' 'Regal' 'Pacifica' 'GLC' 'CX-9' 'Avalon'
 'Renegade' 'Sedona' 'Edge' 'Enclave' 'Expedition' 'Camaro' 'Forte'
 'Patriot' 'Tundra' 'Sonata' 'Verano' 'TSX' 'Z' 'Legacy' 'Avalanche'
 'Transit' 'Ram' 'Dakota' 'XF' 'ATS' 'CC' 'X3' 'Odyssey' 'Equinox' 'RDX'
 'MKX' 'Tacoma' 'FR-S' '200' 'SRX' 'Envoy' 'PT' 'Spectra' 'LX' 'E-Class'
 'Terrain' 'Liberty' 'Town' 'GL-Class' '2' 'CX-5' 'GLE' 'TLX' 'Cadenza'
 'SLK' 'S60' 'A3' 'Beetle' 'Genesis' 'X6' 'Titan' '1500' 'Frontier'
 'Forester' 'Sorento' 'Mirage' '2500' 'GX' 'Eos' 'XT5' 'Sequoia' 'Yukon'
 'F-350' 'SQ5' 'New' 'RSX' 'DTS' 'WRX' 'Ridgeline' 'Cayman' 'S4' '500' 'iM'
 'Flex' 'Spark' 'M4' 'Veloster' 'M3' 'F-Type' 'Impreza' 'R-Class' '500L'
 'Q70' 'Accent' 'C-Max' 'Sportage' 'Q7' 'Tribute' 'Golf' 'Azera' 'QX60'
 'MKS' 'RC' 'X4' 'XJ' 'A8' 'Miata' 'M5' '1' 'CR-Z' 'QX80' 'LS' 'HHR' 'CX-7'
 'Sonic' 'Tucson' 'Touareg' '7' 'C70' 'tC' 'SRT' 'Mazda6' 'S3' 'Crossfire'
 'G6' 'V60' 'TT' 'Armada' 'XTS' 'QX30' 'Cascada' 'CLK' 'X-Type' 'Mazda5'
 'Eurovan' 'Outlook' 'XV' 'Crosstrek' 'Panamera' 'Xterra' 'S80' 'STS'
 'Impala' 'Canyon' '6' '500X' 'Insight' 'SL-Class' 'Cayenne' 'BRZ' 'Matrix'
 'Ranger' 'Solstice' 'Compass' 'Mazda2' 'Lancer' 'Navigator' 'xA' 'K900'
 'LeSabre' 'xB' 'Volt' '3500' 'ELR' 'ProMaster' 'C/V' 'Sunfire' 'Vibe'
 'Fit' 'M35' 'Q60' 'S90' 'Aveo' 'Econoline' 'Macan' 'S-Type' 'CT6'
 'Allroad' 'iA' 'SS' 'FJ' 'SC' 'LC' 'CL-Class' 'NV' 'Quattroporte' 'CX-3'
 'LaCrosse' 'SLC' 'i8' 'i3' '86' 'Cube' 'Boxster' 'Land' 'Yaris' 'Equator'
 'HR-V' '124' 'Q40' 'VUE' 'G8' '9-5' 'xD' 'SX4' '9-3' 'MAZDASPEED3' 'R8'
 'CT' 'RS4' 'Continental' 'MKT' 'Nitro' 'Mariner' 'Envision' 'M6'
 'Commander' 'Eldorado' 'Imperial' 'Alero' 'Neon' 'Torrent' 'Magnum' 'XC70'
 'Equus' 'Leaf' 'G80' 'RX-8' 'B-Series' 'Caravan' 'S-10' 'Ion' 'Eclipse'
 'Mountaineer' 'S6' 'Lucerne' 'Rio5' 'Excursion' 'NV200' 'Forte5'
 'Veracruz' 'MPV' 'Rendezvous' 'V50' 'Z4' 'Captiva' 'Niro' 'RL' 'Caliber'
 'GLS' 'Milan' 'FX37' 'GTI' 'HS' 'Tribeca' 'Express' 'QX56']
----------------------------------------------------------------------
Mileage
[ 99252 102034  15674 ...,  66066  38946  70161]
----------------------------------------------------------------------
Price
[ 9999  6495 33688 ..., 25125 28403 46462]
----------------------------------------------------------------------
Body
['Minivan' 'Sedan' 'SUV' 'Convertible' 'Pickup' 'Coupe' 'Wagon' 'Hatchback'
 'Van' 'Chassis']
----------------------------------------------------------------------
Color
['Black' 'Red' 'Silver' 'White' 'Yellow' 'Gray' 'Brown' 'Beige' 'Blue'
 'Green' 'Gold' 'Turquoise' 'Burgundy' 'Bronze' 'Orange' 'Purple']
----------------------------------------------------------------------
Engine
['6 Cyl' '4 Cyl' '8 Cyl' '5 Cyl' '3 Cyl' '10 Cyl' '2 Cyl' 'Electric'
 '12 Cyl' 'Rotary']
----------------------------------------------------------------------

In [33]:
df.loc[df.Make=='Genesis']

       Year     Make Model  Mileage  Price   Body  Color Engine
12058  2017  Genesis   G80     1988  36984  Sedan  Brown  6 Cyl
19355  2017  Genesis   G80    11175  33989  Sedan  Black  6 Cyl

In [34]:
df.loc[df.Model=='Genesis']

       Year     Make    Model  Mileage  Price   Body   Color Engine
893    2015  Hyundai  Genesis    33317  25995  Sedan   White  6 Cyl
4184   2015  Hyundai  Genesis    33317  25995  Sedan   White  6 Cyl
4978   2015  Hyundai  Genesis    23739  23587  Sedan    Gray  6 Cyl
5821   2015  Hyundai  Genesis    39625  25991  Sedan   White  6 Cyl
6938   2015  Hyundai  Genesis    49697  27000  Sedan  Silver  8 Cyl
8025   2015  Hyundai  Genesis    15786  26750  Sedan    Gray  6 Cyl
10886  2016  Hyundai  Genesis    30780  18990  Coupe    Gray  6 Cyl
11292  2015  Hyundai  Genesis    23382  25600  Sedan  Silver  6 Cyl
11293  2015  Hyundai  Genesis    22625  25600  Sedan   Black  6 Cyl
11499  2015  Hyundai  Genesis    39625  25991  Sedan   White  6 Cyl
12401  2013  Hyundai  Genesis    29225  17500  Sedan  Silver  6 Cyl
12546  2015  Hyundai  Genesis    37911  25290  Sedan    Gray  6 Cyl
12706  2015  Hyundai  Genesis    16540  25452  Sedan    Gray  6 Cyl
13155  2015  Hyundai  Genesis    19091  19499  Coupe   White  6 Cyl
13396  2015  Hyundai  Genesis    33295  29400  Sedan   Black  8 Cyl
13397  2015  Hyundai  Genesis    33675  27300  Sedan   Black  6 Cyl
13398  2015  Hyundai  Genesis    25878  28200  Sedan  Silver  6 Cyl
13405  2015  Hyundai  Genesis    23987  30500  Sedan    Gray  8 Cyl
13406  2015  Hyundai  Genesis    31593  27600  Sedan   White  6 Cyl
13407  2015  Hyundai  Genesis    36705  27100  Sedan   Black  6 Cyl
13408  2013  Hyundai  Genesis   104465  12500  Sedan  Silver  6 Cyl
13410  2015  Hyundai  Genesis    39625  25991  Sedan   White  6 Cyl
13413  2015  Hyundai  Genesis    40385  28400  Sedan   Black  8 Cyl
13757  2011  Hyundai  Genesis   106841   9250  Sedan  Silver  6 Cyl
13847  2015  Hyundai  Genesis    26200  27995  Sedan    Gray  8 Cyl
13918  2015  Hyundai  Genesis    13958  26998  Sedan   Black  6 Cyl
13921  2015  Hyundai  Genesis    37093  22988  Sedan   Black  6 Cyl
13972  2009  Hyundai  Genesis   141055   7550  Sedan    Gray  8 Cyl
14432  2009  Hyundai  Genesis   145737   7300  Sedan  Silver  8 Cyl
14747  2015  Hyundai  Genesis    20608  26990  Sedan     Red  6 Cyl
14815  2014  Hyundai  Genesis    47295  17686  Sedan    Gray  6 Cyl
15211  2015  Hyundai  Genesis    15786  26750  Sedan    Gray  6 Cyl
15283  2013  Hyundai  Genesis    64389  13725  Sedan   White  6 Cyl
15577  2015  Hyundai  Genesis    37911  25290  Sedan    Gray  6 Cyl
16368  2015  Hyundai  Genesis    23093  25755  Sedan   White  6 Cyl
17081  2015  Hyundai  Genesis    23392  26395  Sedan  Silver  6 Cyl
17483  2013  Hyundai  Genesis    66680  16995  Sedan  Silver  6 Cyl
17804  2015  Hyundai  Genesis    75950  19500  Sedan  Silver  6 Cyl
18334  2015  Hyundai  Genesis    23382  25600  Sedan  Silver  6 Cyl
18338  2015  Hyundai  Genesis    22625  25600  Sedan   Black  6 Cyl
19985  2015  Hyundai  Genesis    37911  25290  Sedan    Gray  6 Cyl
20104  2015  Hyundai  Genesis    33317  25995  Sedan   White  6 Cyl
21124  2011  Hyundai  Genesis   106841   9250  Sedan  Silver  6 Cyl
21446  2009  Hyundai  Genesis   145737   7300  Sedan  Silver  8 Cyl

In [35]:
df = df.loc[df.Make!='Genesis']
print("-"*10 + " Drop $Make == Genesis " + "-"*10)
print('It\s a model of Hyundai, not a make')
print(df.shape)

---------- Drop $Make == Genesis ----------
It\s a model of Hyundai, not a make
(20967, 8)

In [36]:
df

,Year,Make,Model,Mileage,Price,Body,Color,Engine
0,2014,Dodge,Grand,99252,9999,Minivan,Black,6 Cyl
1,2014,Dodge,Avenger,102034,6495,Sedan,Black,4 Cyl
2,2016,Jeep,Wrangler,15674,33688,SUV,Red,6 Cyl
3,2011,BMW,3,100273,10966,Convertible,Silver,6 Cyl
4,2015,Ford,Explorer,23640,24983,SUV,White,6 Cyl
5,2013,Nissan,Juke,34662,12917,SUV,Black,4 Cyl
6,2015,Ford,F-250,59829,41999,Pickup,White,8 Cyl
7,2017,GMC,Sierra,11811,37688,Pickup,Black,8 Cyl
8,2017,Chevrolet,Cruze,23276,12988,Sedan,Silver,4 Cyl
9,2016,Ford,Mustang,14231,26455,Coupe,Yellow,8 Cyl
10,2015,Lincoln,MKC,58492,18982,SUV,Black,4 Cyl
11,2011,Honda,Pilot,133295,11259,SUV,Gray,6 Cyl
12,2015,Dodge,Challenger,41904,17998,Coupe,Black,6 Cyl
13,2016,Kia,Rio,15450,9997,Sedan,White,4 Cyl
14,2013,Chevrolet,Suburban,79457,23995,SUV,Black,8 Cyl
15,2015,Toyota,4Runner,46599,31888,SUV,Silver,6 Cyl
16,2016,Chevrolet,Trax,14124,13695,SUV,Red,4 Cyl
17,2015,Chevrolet,Suburban,25192,41884,SUV,Black,8 Cyl
18,2016,Lincoln,MKC,8138,27966,SUV,Silver,4 Cyl
19,2016,GMC,Sierra,10914,29995,Pickup,Red,8 Cyl
20,2015,Mercedes-Benz,C-Class,20773,23995,Coupe,Black,4 Cyl
21,2015,Ford,F-150,22823,38499,Pickup,Brown,8 Cyl
22,2015,Chevrolet,Tahoe,50095,41995,SUV,Beige,8 Cyl
23,2016,Kia,Optima,11484,22982,Sedan,Black,4 Cyl
24,2016,Mitsubishi,Outlander,15086,16992,SUV,Silver,4 Cyl
25,2013,Ford,Escape,95793,9999,SUV,Gray,4 Cyl
26,2007,Infiniti,G35,112457,6999,Sedan,White,6 Cyl
27,2014,Infiniti,Q50,87981,15999,Sedan,Gray,6 Cyl
28,2015,Nissan,Rogue,80263,12999,SUV,White,4 Cyl
29,2014,Infiniti,Q50,32808,18999,Sedan,Black,6 Cyl
...,...,...,...,...,...,...,...,...
21721,2016,Jeep,Cherokee,36350,21997,SUV,Gray,4 Cyl
21722,2016,Ram,1500,19821,46740,Pickup,White,8 Cyl
21723,2017,Honda,Accord,8843,29995,Sedan,Silver,4 Cyl
21724,2016,Honda,Fit,31984,14998,Hatchback,Silver,4 Cyl
21725,2015,Jeep,Renegade,26035,26915,SUV,Beige,4 Cyl
21726,2016,Honda,HR-V,25529,20998,SUV,Red,4 Cyl
21727,2016,Ford,Escape,26989,21999,SUV,Red,4 Cyl
21728,2017,Toyota,Tacoma,13138,31656,Pickup,Silver,6 Cyl
21729,2015,Hyundai,Elantra,30384,11732,Sedan,Black,4 Cyl
21730,2012,Honda,Accord,53297,14647,Sedan,Black,6 Cyl
21731,2015,Ford,F-150,26143,30862,Pickup,White,6 Cyl
21732,2016,GMC,Terrain,31568,28615,SUV,Red,6 Cyl
21734,2013,Ford,Escape,41579,14960,SUV,Brown,4 Cyl
21735,2010,Honda,Odyssey,87802,12389,Minivan,White,6 Cyl
21736,2015,Volkswagen,Tiguan,29481,17651,SUV,Silver,4 Cyl
21737,2016,GMC,Canyon,5648,31394,Pickup,Gray,6 Cyl
21738,2011,Cadillac,CTS,71462,15640,Coupe,Silver,6 Cyl
21739,2015,Kia,Soul,37645,12805,Wagon,Yellow,4 Cyl
21740,2017,Nissan,Versa,4443,10742,Sedan,Blue,4 Cyl
21741,2016,Toyota,Tacoma,36771,28996,Pickup,Blue,6 Cyl
21742,2015,Toyota,RAV4,38166,18407,SUV,White,4 Cyl
21743,2016,Ford,F-150,11982,22980,Pickup,Red,6 Cyl
21744,2015,Cadillac,SRX,38741,25125,SUV,Black,6 Cyl
21745,2016,Nissan,Rogue,28475,18830,SUV,White,4 Cyl
21746,2007,Ford,Expedition,100977,7940,SUV,Gold,8 Cyl
21747,2016,Honda,Civic,45000,19460,Sedan,Blue,4 Cyl
21748,2016,Jeep,Patriot,66066,10900,SUV,White,4 Cyl
21749,2015,Ford,Explorer,38946,28403,SUV,Brown,6 Cyl
21750,2015,Ford,F-350,70161,46462,Pickup,Black,8 Cyl
21751,2014,Chevrolet,Silverado,14197,27000,Pickup,Blue,8 Cyl

In [37]:
# Add Make_Country info
print(len(df.Make.unique()))

df.Make.unique()

39

array(['Dodge', 'Jeep', 'BMW', 'Ford', 'Nissan', 'GMC', 'Chevrolet',
       'Lincoln', 'Honda', 'Kia', 'Toyota', 'Mercedes-Benz', 'Mitsubishi',
       'Infiniti', 'Cadillac', 'Hummer', 'Maserati', 'Volkswagen',
       'Subaru', 'Audi', 'Mini', 'Lexus', 'Acura', 'Mazda', 'Volvo',
       'Hyundai', 'Buick', 'Porsche', 'Chrysler', 'Jaguar', 'Scion', 'Ram',
       'Fiat', 'Pontiac', 'Saturn', 'Mercury', 'Suzuki', 'Saab',
       'Oldsmobile'], dtype=object)

In [38]:
make_country_dict = {'Dodge':'USA', 'Jeep':'USA', 'BMW':'Germany', 'Ford':'USA', 'Nissan':'Japan', 'GMC':'USA', 'Chevrolet':'USA',
                    'Lincoln':'USA', 'Honda':'Japan', 'Kia':'Korea', 'Toyota':'Japan', 'Mercedes-Benz':'Germany', 'Mitsubishi':'Japan',
                    'Infiniti':'Japan', 'Cadillac':'USA', 'Hummer':'USA', 'Maserati':'Italy', 'Volkswagen':'Germany',
                    'Subaru':'Japan', 'Audi':'Germany', 'Mini':'UK', 'Lexus':'Japan', 'Acura':'Japan', 'Mazda':'Japan', 'Volvo':'Sweden',
                    'Hyundai':'Korea', 'Buick':'USA', 'Porsche':'Germany', 'Chrysler':'USA', 'Jaguar':'UK', 'Scion':'Japan', 'Ram':'USA',
                    'Fiat':'Italy', 'Pontiac':'USA', 'Saturn':'USA', 'Mercury':'USA', 'Suzuki':'Japan', 'Saab':'Sweden',
                    'Oldsmobile':'USA'}

In [39]:
isinstance(make_country_dict, dict)

True

In [40]:
make_country_df = pd.DataFrame(list(make_country_dict.items()), columns= ['Make','Country'])
make_country_df

             Make  Country
0           Dodge      USA
1            Jeep      USA
2             BMW  Germany
3            Ford      USA
4          Nissan    Japan
5             GMC      USA
6       Chevrolet      USA
7         Lincoln      USA
8           Honda    Japan
9             Kia    Korea
10         Toyota    Japan
11  Mercedes-Benz  Germany
12     Mitsubishi    Japan
13       Infiniti    Japan
14       Cadillac      USA
15         Hummer      USA
16       Maserati    Italy
17     Volkswagen  Germany
18         Subaru    Japan
19           Audi  Germany
20           Mini       UK
21          Lexus    Japan
22          Acura    Japan
23          Mazda    Japan
24          Volvo   Sweden
25        Hyundai    Korea
26          Buick      USA
27        Porsche  Germany
28       Chrysler      USA
29         Jaguar       UK
30          Scion    Japan
31            Ram      USA
32           Fiat    Italy
33        Pontiac      USA
34         Saturn      USA
35        Mercury      USA
36         Suzuki    Japan
37           Saab   Sweden
38     Oldsmobile      USA

In [41]:
df = pd.merge(df, make_country_df, on='Make')

In [42]:
df.to_csv('cars2nd.csv',index=False)
df1 = pd.read_csv('cars2nd.csv')

print(df1.shape)

df1[df1.Country=='Sweden'].head()

(20967, 9)

       Year   Make Model  Mileage  Price   Body   Color Engine Country
18935  2005  Volvo  XC90    97466   6995    SUV    Gray  6 Cyl  Sweden
18936  2014  Volvo  XC60    30345  24906    SUV  Silver  6 Cyl  Sweden
18937  2008  Volvo   V70   129000   6995  Wagon   White  6 Cyl  Sweden
18938  2005  Volvo  XC90    97466   6995    SUV    Gray  6 Cyl  Sweden
18939  2013  Volvo   S60    21409  15000  Sedan    Gray  5 Cyl  Sweden